# Generated by Django 5.1.2 on 2024-10-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_superhero_description_superhero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='heroes/'),
        ),
    ]
