alerts:
- disabled: true
  rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
domains:
- domain: nocointerlock.com
  type: PRIMARY
  zone: nocointerlock.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: pythonwebapps
    match:
      path:
        prefix: /
  - component:
      name: pythonwebapp
    match:
      path:
        prefix: /staticfiles/admin
name: seahorse-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: DATABASE_ENGINE
    scope: RUN_AND_BUILD_TIME
    value: django.db.backends.postgresql
  - key: DATABASE_NAME
    scope: RUN_AND_BUILD_TIME
    value: config/seahorse.db
  github:
    branch: my-bacs-350-code
    deploy_on_push: true
    repo: an5onc/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: pythonwebapps
  run_command: gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: student/Project9/
static_sites:
- environment_slug: html
  github:
    branch: my-bacs-350-code
    deploy_on_push: true
    repo: an5onc/PythonWebApps
  name: pythonwebapp
  source_dir: student/Project9/
