# Generated by Django 5.1.1 on 2024-10-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='strengths',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='weaknesses',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
